<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class UserSeeder extends Seeder
{
    public function run(): void
    {
        $password = '$2y$12$U2Y15a7fbhTyEpad6NP0u.pbbvScpODUsbzZXUQMnaAGUA.fuPyli';

        DB::table('users')->insert([
            // ===== ADMIN =====
            [
                'username' => 'TMMC-ADMIN',
                'email' => 'admin@hospital.vn',
                'full_name' => 'Quản trị hệ thống',
                'password' => $password,
                'department_id' => null,
                'role_code' => 'ADMIN',
                'active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // ===== 21 KHOA / PHÒNG =====
            [
                'username' => 'TMMC-CDHA',
                'email' => 'cdha@hospital.vn',
                'full_name' => 'Trưởng Khoa Chuẩn Đoán Hình Ảnh',
                'password' => $password,
                'department_id' => 1,
                'role_code' => 'DEPARTMENT',
                'active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'username' => 'TMMC-XETNGHIEM',
                'email' => 'xetnghiem@hospital.vn',
                'full_name' => 'Trưởng Khoa Xét Nghiệm',
                'password' => $password,
                'department_id' => 2,
                'role_code' => 'DEPARTMENT',
                'active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'username' => 'TMMC-CAPCUU',
                'email' => 'capcuu@hospital.vn',
                'full_name' => 'Trưởng Khoa Cấp Cứu',
                'password' => $password,
                'department_id' => 3,
                'role_code' => 'DEPARTMENT',
                'active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'username' => 'TMMC-PHONGMO',
                'email' => 'phongmo@hospital.vn',
                'full_name' => 'Phụ Trách Phòng Mổ',
                'password' => $password,
                'department_id' => 4,
                'role_code' => 'DEPARTMENT',
                'active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'username' => 'TMMC-DUOC',
                'email' => 'duoc@hospital.vn',
                'full_name' => 'Trưởng Khoa Dược',
                'password' => $password,
                'department_id' => 5,
                'role_code' => 'DEPARTMENT',
                'active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'username' => 'TMMC-PHONGKHAM',
                'email' => 'phongkham@hospital.vn',
                'full_name' => 'Trưởng Phòng Khám',
                'password' => $password,
                'department_id' => 6,
                'role_code' => 'DEPARTMENT',
                'active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'username' => 'TMMC-HOISUC',
                'email' => 'hoisuc@hospital.vn',
                'full_name' => 'Trưởng Khoa Hồi Sức',
                'password' => $password,
                'department_id' => 7,
                'role_code' => 'DEPARTMENT',
                'active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'username' => 'TMMC-SAN',
                'email' => 'san@hospital.vn',
                'full_name' => 'Trưởng Khoa Sản',
                'password' => $password,
                'department_id' => 8,
                'role_code' => 'DEPARTMENT',
                'active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'username' => 'TMMC-CSKH',
                'email' => 'cskh@hospital.vn',
                'full_name' => 'Trưởng Phòng Kinh Doanh - CSKH',
                'password' => $password,
                'department_id' => 9,
                'role_code' => 'DEPARTMENT',
                'active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'username' => 'TMMC-NGOAI',
                'email' => 'ngoai@hospital.vn',
                'full_name' => 'Trưởng Khoa Ngoại',
                'password' => $password,
                'department_id' => 10,
                'role_code' => 'DEPARTMENT',
                'active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'username' => 'TMMC-NHI',
                'email' => 'nhi@hospital.vn',
                'full_name' => 'Trưởng Khoa Nhi',
                'password' => $password,
                'department_id' => 11,
                'role_code' => 'DEPARTMENT',
                'active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'username' => 'TMMC-HCNS',
                'email' => 'hcns@hospital.vn',
                'full_name' => 'Trưởng Phòng Hành Chính - Nhân Sự',
                'password' => $password,
                'department_id' => 12,
                'role_code' => 'DEPARTMENT',
                'active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'username' => 'TMMC-HOTRODV',
                'email' => 'hotrodv@hospital.vn',
                'full_name' => 'Trưởng Phòng Hỗ Trợ Dịch Vụ',
                'password' => $password,
                'department_id' => 13,
                'role_code' => 'DEPARTMENT',
                'active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'username' => 'TMMC-KETOAN',
                'email' => 'ketoan@hospital.vn',
                'full_name' => 'Trưởng Phòng Kế Toán',
                'password' => $password,
                'department_id' => 14,
                'role_code' => 'DEPARTMENT',
                'active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'username' => 'TMMC-NOI',
                'email' => 'noi@hospital.vn',
                'full_name' => 'Trưởng Khoa Nội',
                'password' => $password,
                'department_id' => 15,
                'role_code' => 'DEPARTMENT',
                'active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'username' => 'TMMC-YVU',
                'email' => 'yvu@hospital.vn',
                'full_name' => 'Trưởng Phòng Y Vụ',
                'password' => $password,
                'department_id' => 16,
                'role_code' => 'DEPARTMENT',
                'active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'username' => 'TMMC-KHO-VPP',
                'email' => 'khovpp@hospital.vn',
                'full_name' => 'Quản Lý Kho Văn Phòng Phẩm',
                'password' => $password,
                'department_id' => 17,
                'role_code' => 'DEPARTMENT',
                'active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'username' => 'TMMC-DALIEU',
                'email' => 'dalieu@hospital.vn',
                'full_name' => 'Trưởng Khoa Da Liễu',
                'password' => $password,
                'department_id' => 18,
                'role_code' => 'DEPARTMENT',
                'active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'username' => 'TMMC-KSNK',
                'email' => 'ksnk@hospital.vn',
                'full_name' => 'Trưởng Khoa Kiểm Soát Nhiễm Khuẩn',
                'password' => $password,
                'department_id' => 19,
                'role_code' => 'DEPARTMENT',
                'active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'username' => 'TMMC-DSA',
                'email' => 'dsa@hospital.vn',
                'full_name' => 'Trưởng Khoa DSA',
                'password' => $password,
                'department_id' => 20,
                'role_code' => 'DEPARTMENT',
                'active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'username' => 'TMMC-TDCN',
                'email' => 'tdcn@hospital.vn',
                'full_name' => 'Trưởng Phòng Thăm Dò Chức Năng',
                'password' => $password,
                'department_id' => 21,
                'role_code' => 'DEPARTMENT',
                'active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}
